version: '3.1'

services:
  node:
    image: node:latest
    container_name: node
    expose:
      - "3000"
    ports:
      - "3001:3000"
    working_dir: /home/node/app
    volumes:
      - .:/home/node/app
      - ./node_modules:/home/node/app/node_modules
    environment:
      - NODE_ENV=development
    command: >
      sh -c "npm install &&
            npm run start"

